### PR TITLE
Issue19

### PR DESCRIPTION
**Pull request by weicai2015**
Fixed issue19: layout and data display of page step3

### CODE REVIEW

**Comment by weicai2015** [comment]
Cheh:
I just have a couple of questions:
1. I found out that it was hard to have JQuery code running within embedded framework, so I wrote javascript instead for step1.jsp, to dynamically populate state drop down list when "US" and/or "CA" is selected as country, also for the "other country" fields to showup/hide. I just leave the javascript code within the same jsp piece. Is this OK? if yes, I can check in this code today.
2. I don't know why the buttons on step3.jsp not working for me. I attached the error message below. If you have any idea on top of your head, please advise me, otherwise, DO NOT spend time figuring it out, your time is precious right now, let me continue struggling with it. :)
   Thanks and Blessings,Wei------------------------

HTTP Status 500 - Request processing failed; nested exception is org.springframework.webflow.execution.repository.FlowExecutionRestorationFailureException: A problem occurred restoring the flow execution with key 'e1s3'
type Exception reportmessage Request processing failed; nested exception is org.springframework.webflow.execution.repository.FlowExecutionRestorationFailureException: A problem occurred restoring the flow execution with key 'e1s3'description The server encountered an internal error that prevented it from fulfilling this request.exception

**Comment by chehhoo** [comment]
I checked in latest changes recently. Did the new code fix the problem you see ? When you check in code, try avoid check in code that not belong to the functionality such as RAR, ZIP or temporary files.

**Comment by weicai2015** [comment]
Cheh:
I checked in code for issue23 for the checkbox on review page, and created a pull request. Please review it.
I won't be meeting with you tomorrow morning. I feel a little tired these days, as I found out that I have anemia earlier this month. Please pray for me. Weimin is out of town this week. Plus this month I am in my bible study leadership training, which was postponed from December, this week is the last week. So, hopefully I will have more time and energy to work with you next week.
Blessings,Wei

**Comment by weicai2015** [comment]
Cheh:
I tried to run the new code, but at very beginning I got the following error:
java.io.FileNotFoundException: class path resource [registration-config.properties] cannot be opened because it does not exist

Where this file should be? I did git pull from github.com for all the new code, I don't know why my local doesn't have it.
Thanks,Wei

**Comment by chehhoo** [comment]
Oh, forget to tell you. Copy registration-config.properties from
src/main/resources to your Tomcat lib folder. registration-config.properties
will not include in the build because it contains environment specified
information. It will be install separately so that we have flexibility to
run the web application in different place without changing the code, but
only change the properties file.

**Pull request merged**
